[2023-01-05T08:34:21.437+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: import_to_test_table_v1.get_cash_flow_data manual__2023-01-05T08:34:16.307030+00:00 [queued]>
[2023-01-05T08:34:21.447+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: import_to_test_table_v1.get_cash_flow_data manual__2023-01-05T08:34:16.307030+00:00 [queued]>
[2023-01-05T08:34:21.447+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-05T08:34:21.447+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-01-05T08:34:21.447+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-05T08:34:21.536+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): get_cash_flow_data> on 2023-01-05 08:34:16.307030+00:00
[2023-01-05T08:34:21.546+0000] {standard_task_runner.py:55} INFO - Started process 2333 to run task
[2023-01-05T08:34:21.551+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'import_to_test_table_v1', 'get_cash_flow_data', 'manual__2023-01-05T08:34:16.307030+00:00', '--job-id', '199', '--raw', '--subdir', 'DAGS_FOLDER/import_to_test_table.py', '--cfg-path', '/tmp/tmpbcpfcnlf']
[2023-01-05T08:34:21.553+0000] {standard_task_runner.py:83} INFO - Job 199: Subtask get_cash_flow_data
[2023-01-05T08:34:21.652+0000] {task_command.py:389} INFO - Running <TaskInstance: import_to_test_table_v1.get_cash_flow_data manual__2023-01-05T08:34:16.307030+00:00 [running]> on host d84d515babd0
[2023-01-05T08:34:21.895+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=import_to_test_table_v1
AIRFLOW_CTX_TASK_ID=get_cash_flow_data
AIRFLOW_CTX_EXECUTION_DATE=2023-01-05T08:34:16.307030+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-05T08:34:16.307030+00:00
[2023-01-05T08:40:49.828+0000] {local_task_job.py:224} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-01-05T08:40:49.831+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 2333. PIDs of all processes in the group: [2333]
[2023-01-05T08:40:49.831+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 2333
[2023-01-05T08:40:49.831+0000] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-01-05T08:41:49.845+0000] {process_utils.py:147} WARNING - process psutil.Process(pid=2333, name='airflow task ru', status='sleeping', started='08:34:20') did not respond to SIGTERM. Trying SIGKILL
[2023-01-05T08:41:49.846+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGKILL to group 2333
[2023-01-05T08:41:49.859+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2333, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='08:34:20') (2333) terminated with exit code Negsignal.SIGKILL
[2023-01-05T08:41:49.860+0000] {standard_task_runner.py:170} ERROR - Job 199 was killed before it finished (likely due to running out of memory)
