[2022-12-28T07:42:06.466+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: new_table_and_data_import_dag_v1.get_cash_flow_data manual__2022-12-28T07:42:02.270330+00:00 [queued]>
[2022-12-28T07:42:06.477+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: new_table_and_data_import_dag_v1.get_cash_flow_data manual__2022-12-28T07:42:02.270330+00:00 [queued]>
[2022-12-28T07:42:06.477+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-28T07:42:06.478+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-28T07:42:06.478+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-28T07:42:06.519+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): get_cash_flow_data> on 2022-12-28 07:42:02.270330+00:00
[2022-12-28T07:42:06.525+0000] {standard_task_runner.py:55} INFO - Started process 1360 to run task
[2022-12-28T07:42:06.529+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'new_table_and_data_import_dag_v1', 'get_cash_flow_data', 'manual__2022-12-28T07:42:02.270330+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/new_table_and_data_import_dag.py', '--cfg-path', '/tmp/tmpxy96feo5']
[2022-12-28T07:42:06.531+0000] {standard_task_runner.py:83} INFO - Job 13: Subtask get_cash_flow_data
[2022-12-28T07:42:06.628+0000] {task_command.py:389} INFO - Running <TaskInstance: new_table_and_data_import_dag_v1.get_cash_flow_data manual__2022-12-28T07:42:02.270330+00:00 [running]> on host 016cb28b89a1
[2022-12-28T07:42:07.288+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=new_table_and_data_import_dag_v1
AIRFLOW_CTX_TASK_ID=get_cash_flow_data
AIRFLOW_CTX_EXECUTION_DATE=2022-12-28T07:42:02.270330+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-28T07:42:02.270330+00:00
[2022-12-28T07:42:14.335+0000] {python.py:177} INFO - Done. Returned value was:                      investCost  fromInvest  ...  fromSale  freeCashFlow
ticker year quarter                          ...                        
ABR    2022 3                 0        -124  ...        21          13.0
ABI    2022 3                -1         -35  ...        22         152.0
ABC    2022 3                 0          46  ...        82        -620.0
ABB    2022 3               -29         -16  ...      -748           0.0
AAV    2022 3                 0          41  ...       -40          66.0
...                         ...         ...  ...       ...           ...
AAA    2007 5               -56         -65  ...       -50           NaN
ABC    2006 5                -3          -2  ...        -9           NaN
ABB    2006 5                -6          -6  ...      -245           NaN
AAM    2006 5                -5          -5  ...        25           NaN
ABB    2000 4                 0           0  ...         0           NaN

[357 rows x 5 columns]
[2022-12-28T07:42:14.361+0000] {xcom.py:635} ERROR - Object of type DataFrame is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2022-12-28T07:42:14.362+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2301, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 240, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 627, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 176, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 170, in default
    return super().default(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2022-12-28T07:42:14.372+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=new_table_and_data_import_dag_v1, task_id=get_cash_flow_data, execution_date=20221228T074202, start_date=20221228T074206, end_date=20221228T074214
[2022-12-28T07:42:14.597+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 13 for task get_cash_flow_data (Object of type DataFrame is not JSON serializable; 1360)
[2022-12-28T07:42:14.646+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-28T07:42:14.676+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
